version: '3.8'

services:
  jaded-platform:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PYTHONPATH=/app
      - CEREBRAS_API_KEY=${CEREBRAS_API_KEY}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped

  # Add Julia service
  julia-service:
    image: julia:1.9
    ports:
      - "8001:8001"
    volumes:
      - ./alphafold.jl:/app/alphafold.jl
    command: julia /app/alphafold.jl
    restart: unless-stopped

  # Add Nim service  
  nim-service:
    image: nimlang/nim:1.6.14
    ports:
      - "8022:8022"
    volumes:
      - ./fabric/layer4_native:/app
    working_dir: /app
    command: nim c -r nim_performance.nim
    restart: unless-stopped
